# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
<<<<<<< HEAD
  - iearn-finance/yearn-vaults@0.3.2
=======
  - yearn/yearn-vaults@0.4.2-1
>>>>>>> a0c41a1 (Initialize test_enhancements)
  - OpenZeppelin/openzeppelin-contracts@3.1.0

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.6.12
    remappings:
<<<<<<< HEAD
      - "@yearnvaults=iearn-finance/yearn-vaults@0.3.2"
=======
      - "@yearnvaults=yearn/yearn-vaults@0.4.2-1"
>>>>>>> a0c41a1 (Initialize test_enhancements)
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"

reports:
  exclude_contracts:
    - SafeMath
